services:
  - type: web
    name: war-sim
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class gthread --workers 1 --threads 4 --bind 0.0.0.0:$PORT --timeout 120
